export { default as INPUT } from './input'
export { default as BUTTON } from './button'
export { default as BUTTONSIDEBAR } from './button-sidebar'
export { default as LANGUAGEPOTION } from './language-select-optins'
export { default as SELECTOPTIOS } from './options-select-sciences'
export { default as BUTTONEXIT } from './button-exit'
export { default as CARDCLASSES } from './card-clasess'
export { default as CLASSSCHEDULE } from './class schedule'
export { default as LOADER } from './loader'
export { default as SELECTTERMS } from './select-term'
export { default as CARDSCHEDULE } from './card-class-scedule'
export { default as TEACHERSUBJECT } from './teacher-subject'