export { default as Home } from './home'
export { default as REGISTER } from './register'
export { default as PROFIL } from './profil'
export { default as PageNoteFound } from './404'
export { default as CLASSSCHEDULE } from './class-schedule'
export { default as GRADERATING } from './grade-rating'
export { default as ATTENDANCE } from './attendance'
