export { default as INPUT } from './input'
export { default as BUTTON } from './button'
export { default as BUTTONSIDEBAR } from './button-sidebar'
export { default as LANGUAGEPOTION } from './language-select-optins'
export { default as SELECTOPTIOS } from './options-select-sciences'
export { default as BUTTONEXIT } from './button-exit'