export { default as Home } from './home'
export { default as REGISTER } from './register'
export { default as PROFIL } from './profil'
export { default as PageNoteFound } from './404'
export { default as ListOfClasses} from './list-of-classes'
export { default as ListOfClassesID} from './list-of-classes-id'