export { default as Home } from './home'
export { default as REGISTER } from './register'
export { default as PROFIL } from './profil'
export { default as PageNoteFound } from './404'
export { default as ListOfClasses } from './list-of-classes'
export { default as ListOfClassesID } from './list-of-classes-id'
export { default as CLASSSCHEDULES } from './class-schedule'
export { default as CLASSSCHEDULESID } from './class-schedule-id'
export { default as TEACHER } from './teacher'
export { default as STUDENTS } from './students'
export { default as LISTOFSUBJECTS } from './list-of-subjects'
// export { default as MYCLASSESID } from './my-clsses-id'
export { default as ADDSTUDENT } from './add-students'
